set_property PACKAGE_PIN R11 [get_ports a]
set_property PACKAGE_PIN V1 [get_ports b]
set_property PACKAGE_PIN F6 [get_ports c]
set_property PACKAGE_PIN G4 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports d]
