# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/LANGLANG/Desktop/vivado/langlang_fulladd/langlang_fulladd.srcs/sources_1/ip/iphalf_add/iphalf_add.xci
# IP: The module: 'iphalf_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/LANGLANG/Desktop/vivado/langlang_fulladd/langlang_fulladd.srcs/sources_1/ip/iphalf_add/constrs_1/new/top_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iphalf_add'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/LANGLANG/Desktop/vivado/langlang_fulladd/langlang_fulladd.srcs/sources_1/ip/iphalf_add/iphalf_add.xci
# IP: The module: 'iphalf_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/LANGLANG/Desktop/vivado/langlang_fulladd/langlang_fulladd.srcs/sources_1/ip/iphalf_add/constrs_1/new/top_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iphalf_add'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
