set_property PACKAGE_PIN F6 [get_ports result]
set_property PACKAGE_PIN R11 [get_ports s1]
set_property PACKAGE_PIN R17 [get_ports s2]
set_property PACKAGE_PIN R15 [get_ports s3]
set_property IOSTANDARD LVCMOS33 [get_ports result]
set_property IOSTANDARD LVCMOS33 [get_ports s1]
set_property IOSTANDARD LVCMOS33 [get_ports s2]
set_property IOSTANDARD LVCMOS33 [get_ports s3]
